### ISSUE TITLE
Issue 10

### ISSUE THREAD

**Issue by DennyTim** [Rahul-k25/Simple-Photo-Page#10]
https://github.com/Rahul-k25/Simple-Photo-Page/blob/d0d9c02fe2db0e29fdc71c3bd66b7af35c1a041e/styles.css#L4

Contextually right way with indents, while `body` selector is used, but it's not the correct way to use internal indents for the whole page. Better to bring a special container for each section of the page.

If you wanna use width restrictions for the page, you need to use the following structure:

```html

<header class="...">
   <div class="container">...</div>
</header>
<main class="...">
   <div class="container">...</div>
</main >
<footer class="...">
   <div class="container">...</div>
</footer>
```

```css
.container {
    width: 960px;
    margin: 0 auto;
    text-align: center; /* can be used optionally if you wanna to align the whole section */
}
```
